<a href="https://colab.research.google.com/github/aliceylu/python/blob/main/Aula_Numpy_02_Verificando_propriedades_dos_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Verificando propriedades de um ndarray

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([4, 2, 1, 4, 4, 6, 2, 9, 6, 2])

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[  9,  78,  29,  27,   5],
       [ 18,  30,  59,  25,  30],
       [ 46,  74,  97,  83, 100],
       [ 45,  63,  54,  37,  70]])

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.40701911, 0.32762304, 0.85386087, 0.46494834, 0.34552711],
        [0.76532226, 0.0595926 , 0.8149593 , 0.09146872, 0.36656679],
        [0.19364469, 0.74397505, 0.45883761, 0.00597793, 0.58269711],
        [0.11641762, 0.84528394, 0.64857901, 0.04333571, 0.58818136]],

       [[0.90125598, 0.73345489, 0.23247886, 0.96806256, 0.20707457],
        [0.51659697, 0.53108092, 0.7719108 , 0.73066541, 0.4466398 ],
        [0.91325233, 0.5153609 , 0.53406668, 0.70883018, 0.42974787],
        [0.33944542, 0.15886368, 0.83561217, 0.80016797, 0.17478777]],

       [[0.31936389, 0.57512039, 0.5103634 , 0.90019683, 0.68592384],
        [0.04490373, 0.0569804 , 0.50132156, 0.25036805, 0.03260688],
        [0.56727853, 0.7933424 , 0.48995507, 0.53263481, 0.8117603 ],
        [0.34489874, 0.4036507 , 0.93099704, 0.10416625, 0.75738269]]])

### Verificando o formato e quantidade de dimensões de um array - shape e dim

In [5]:
# A propriedade shape retorna o formato do array
a1D.shape

(10,)

In [6]:
a2D.shape

(4, 5)

In [7]:
a3D.shape

(3, 4, 5)

In [8]:
# A propriedade ndim retorna o números de dimensões do array
a1D.ndim

1

In [9]:
a2D.ndim

2

In [10]:


a3D.ndim

3

### Verificando o tamanho das dimensões de um array - len

In [11]:
len(a1D) # Retorna o tamanho da 1a dimensão (quantidade de colunas)

10

In [12]:
len(a2D) # Retorna o tamanho da 1a dimensão (quantidade de linhas)

4

In [13]:
len(a2D[0]) # Retorna o tamanho da 2a dimensão (quantidade de colunas)

5

In [14]:
len(a3D) # Retorna o tamanho da 1a dimensão (quantidade de páginas)

3

In [15]:
len(a3D[0]) # Retorna o tamanho da 2a dimensão (quantidade de linhas)

4

In [16]:
len(a3D[0][0]) # Retorna o tamanho da 3a dimensão (quantidade de colunas)

5

### Verificando a quantidade de elementos de um array - size

In [17]:
a1D.size

10

In [18]:
a2D.size

20

In [19]:
a3D.size

60

### Verificando o tipo dos elementos um array - dtype

In [20]:
a1D.dtype

dtype('int64')

In [21]:
a1D.dtype.name

'int64'

In [22]:
a2D.dtype

dtype('int64')

In [23]:
a2D.dtype.name

'int64'

In [24]:
a3D.dtype

dtype('float64')

In [25]:
a3D.dtype.name

'float64'