# Indexação e fatiamento (slicing)

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([7, 4, 0, 6, 2, 8, 1, 4, 9, 1])

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[ 9, 47, 69, 93, 43],
       [60, 74, 87, 24, 31],
       [86, 91, 38, 87, 58],
       [85, 75, 66,  3, 20]])

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.20077689, 0.19275275, 0.98311763, 0.29831892, 0.40034752],
        [0.81889527, 0.72714572, 0.09146693, 0.33208354, 0.89013518],
        [0.72330325, 0.48348188, 0.9362443 , 0.24980908, 0.96200838],
        [0.67234782, 0.65196623, 0.88683689, 0.83300326, 0.8694458 ]],

       [[0.86533944, 0.47462816, 0.18817122, 0.62288818, 0.4960806 ],
        [0.68749027, 0.13061042, 0.08830027, 0.44535229, 0.90457113],
        [0.40194862, 0.82952579, 0.60863316, 0.89487463, 0.44735627],
        [0.34492371, 0.99881004, 0.56974749, 0.35008089, 0.50254604]],

       [[0.67101738, 0.81931999, 0.87326983, 0.81918305, 0.72081379],
        [0.83804782, 0.4488308 , 0.29033422, 0.97400712, 0.19600404],
        [0.14347321, 0.0434866 , 0.68498206, 0.17155262, 0.48873379],
        [0.26324035, 0.62759357, 0.8062624 , 0.86394872, 0.39475714]]])

### Acessando elementos específicos

In [5]:
# Acessando elementos de um ndarray de 1 dimensão
a1D

array([7, 4, 0, 6, 2, 8, 1, 4, 9, 1])

In [6]:
# nome_do_array[índice]
a1D[0]

7

In [7]:
a1D[2]

0

In [8]:
a1D[-1]

1

In [9]:
indices = [3, 0, -1] # Definindo uma lista com os índices que se deseja acessar
a1D[indices]

array([6, 7, 1])

In [10]:
# Acessando elementos de um ndarray de 2 dimensões
a2D

array([[ 9, 47, 69, 93, 43],
       [60, 74, 87, 24, 31],
       [86, 91, 38, 87, 58],
       [85, 75, 66,  3, 20]])

In [11]:
# nome_da_matriz[linha][coluna]
a2D[1][2]

87

In [12]:
a2D[3][4]

20

In [13]:
indice_lin = [0, 1, 2, 3]
indice_col = [0, 1, 2, 3]

a2D[indice_lin, indice_col]

array([ 9, 74, 38,  3])

In [14]:
indice_lin = [0, 1, 2, 3]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([93, 87, 91, 85])

In [15]:
indice_lin = [3, 2, 1, 0]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([ 3, 38, 74,  9])

In [16]:
a2D[:,[0,1,2,0]]

array([[ 9, 47, 69,  9],
       [60, 74, 87, 60],
       [86, 91, 38, 86],
       [85, 75, 66, 85]])

In [17]:
a2D[:,[0,1,2,0]][[1, 0, 1, 0]] #todas as linhas / colunas 0,1,2,0 / retorna linha 1,0,1,0

array([[60, 74, 87, 60],
       [ 9, 47, 69,  9],
       [60, 74, 87, 60],
       [ 9, 47, 69,  9]])

In [18]:
a2D

array([[ 9, 47, 69, 93, 43],
       [60, 74, 87, 24, 31],
       [86, 91, 38, 87, 58],
       [85, 75, 66,  3, 20]])

In [19]:
a2D[[1, 0, 1, 0]][:,[0,1,2,0]] #linha 1,0,1,0 / de todas essas linhas retorna 0,1,2,0 colunas

array([[60, 74, 87, 60],
       [ 9, 47, 69,  9],
       [60, 74, 87, 60],
       [ 9, 47, 69,  9]])

In [20]:
# Acessando elementos de um ndarray de 3 dimensões
a3D

array([[[0.20077689, 0.19275275, 0.98311763, 0.29831892, 0.40034752],
        [0.81889527, 0.72714572, 0.09146693, 0.33208354, 0.89013518],
        [0.72330325, 0.48348188, 0.9362443 , 0.24980908, 0.96200838],
        [0.67234782, 0.65196623, 0.88683689, 0.83300326, 0.8694458 ]],

       [[0.86533944, 0.47462816, 0.18817122, 0.62288818, 0.4960806 ],
        [0.68749027, 0.13061042, 0.08830027, 0.44535229, 0.90457113],
        [0.40194862, 0.82952579, 0.60863316, 0.89487463, 0.44735627],
        [0.34492371, 0.99881004, 0.56974749, 0.35008089, 0.50254604]],

       [[0.67101738, 0.81931999, 0.87326983, 0.81918305, 0.72081379],
        [0.83804782, 0.4488308 , 0.29033422, 0.97400712, 0.19600404],
        [0.14347321, 0.0434866 , 0.68498206, 0.17155262, 0.48873379],
        [0.26324035, 0.62759357, 0.8062624 , 0.86394872, 0.39475714]]])

In [21]:
# nome_do_cubo[página][linha][coluna]
a3D[2][0][3]

0.8191830517577602

In [22]:
a3D[0][3][1]

0.6519662280288058

### Fatiamento (slicing)

In [23]:
# Array de 1 dimensão
a1D

array([7, 4, 0, 6, 2, 8, 1, 4, 9, 1])

In [24]:
a = a1D[1:5] # Índice 1 ao 4
a

array([4, 0, 6, 2])

In [25]:
b = a1D[0:6] # Índice 0 ao 5
b

array([7, 4, 0, 6, 2, 8])

In [26]:
c = a1D[:6] # Do início ao 5
c

array([7, 4, 0, 6, 2, 8])

In [27]:
d = a1D[::2] # Do início ao fim, com passo 2
d

array([7, 0, 2, 1, 9])

In [28]:
e = a1D[-1::-1] # Do final até o início
e

array([1, 9, 4, 1, 8, 2, 6, 0, 4, 7])

In [29]:
# Array de 2 dimensões
a2D

array([[ 9, 47, 69, 93, 43],
       [60, 74, 87, 24, 31],
       [86, 91, 38, 87, 58],
       [85, 75, 66,  3, 20]])

In [30]:
linha0 = a2D[0] # Todos os elementos da linha 0 - outra forma seria: linha0 = a2D[0,:]
linha0

array([ 9, 47, 69, 93, 43])

In [31]:
linha1 = a2D[1,:] # Todos os elementos da linha 1
linha1

array([60, 74, 87, 24, 31])

In [32]:
linha2 = a2D[2,1:4] # Linha 2, colunas 1, 2 e 3
linha2

array([91, 38, 87])

In [33]:
linha3 = a2D[:][3] # a2D[:] retorna toda a matriz, então de toda a matriz queremos a linha 3 a2D[:][3]
linha3

array([85, 75, 66,  3, 20])

In [34]:
coluna2 = a2D[:,2] # De todas as linhas, selecionar a coluna 2
coluna2

array([69, 87, 38, 66])

In [35]:
coluna3 = a2D[1:,3] # Da linha um até a última, selecionar a coluna 3
coluna3

array([24, 87,  3])

In [36]:
# Array de 3 dimensões
a3D

array([[[0.20077689, 0.19275275, 0.98311763, 0.29831892, 0.40034752],
        [0.81889527, 0.72714572, 0.09146693, 0.33208354, 0.89013518],
        [0.72330325, 0.48348188, 0.9362443 , 0.24980908, 0.96200838],
        [0.67234782, 0.65196623, 0.88683689, 0.83300326, 0.8694458 ]],

       [[0.86533944, 0.47462816, 0.18817122, 0.62288818, 0.4960806 ],
        [0.68749027, 0.13061042, 0.08830027, 0.44535229, 0.90457113],
        [0.40194862, 0.82952579, 0.60863316, 0.89487463, 0.44735627],
        [0.34492371, 0.99881004, 0.56974749, 0.35008089, 0.50254604]],

       [[0.67101738, 0.81931999, 0.87326983, 0.81918305, 0.72081379],
        [0.83804782, 0.4488308 , 0.29033422, 0.97400712, 0.19600404],
        [0.14347321, 0.0434866 , 0.68498206, 0.17155262, 0.48873379],
        [0.26324035, 0.62759357, 0.8062624 , 0.86394872, 0.39475714]]])

1D - primeira dimensão -> coluna
2D - primeira dimensão -> linhas
3D - primeira dimensão -> página

In [37]:
# Acessando a página/face 1
face1 = a3D[1]
face1

array([[0.86533944, 0.47462816, 0.18817122, 0.62288818, 0.4960806 ],
       [0.68749027, 0.13061042, 0.08830027, 0.44535229, 0.90457113],
       [0.40194862, 0.82952579, 0.60863316, 0.89487463, 0.44735627],
       [0.34492371, 0.99881004, 0.56974749, 0.35008089, 0.50254604]])

In [38]:
# Acessando uma parte da face1 / página, linhas de 0 a 2 e colunas de 1 a 3
subface1 = a3D[1,0:3, 1:4]
subface1

array([[0.47462816, 0.18817122, 0.62288818],
       [0.13061042, 0.08830027, 0.44535229],
       [0.82952579, 0.60863316, 0.89487463]])

In [39]:
linha2face0 = a3D[0,2] # outra forma: linha2face0 = a3D[0,2,:]
linha2face0

array([0.72330325, 0.48348188, 0.9362443 , 0.24980908, 0.96200838])

In [40]:
a3D

array([[[0.20077689, 0.19275275, 0.98311763, 0.29831892, 0.40034752],
        [0.81889527, 0.72714572, 0.09146693, 0.33208354, 0.89013518],
        [0.72330325, 0.48348188, 0.9362443 , 0.24980908, 0.96200838],
        [0.67234782, 0.65196623, 0.88683689, 0.83300326, 0.8694458 ]],

       [[0.86533944, 0.47462816, 0.18817122, 0.62288818, 0.4960806 ],
        [0.68749027, 0.13061042, 0.08830027, 0.44535229, 0.90457113],
        [0.40194862, 0.82952579, 0.60863316, 0.89487463, 0.44735627],
        [0.34492371, 0.99881004, 0.56974749, 0.35008089, 0.50254604]],

       [[0.67101738, 0.81931999, 0.87326983, 0.81918305, 0.72081379],
        [0.83804782, 0.4488308 , 0.29033422, 0.97400712, 0.19600404],
        [0.14347321, 0.0434866 , 0.68498206, 0.17155262, 0.48873379],
        [0.26324035, 0.62759357, 0.8062624 , 0.86394872, 0.39475714]]])

In [41]:
linha1todasfaces = a3D[:,1] # outra forma: linha1todasfaces = a3D[:,1,:]
linha1todasfaces

array([[0.81889527, 0.72714572, 0.09146693, 0.33208354, 0.89013518],
       [0.68749027, 0.13061042, 0.08830027, 0.44535229, 0.90457113],
       [0.83804782, 0.4488308 , 0.29033422, 0.97400712, 0.19600404]])

In [42]:
coluna3todasfaces = a3D[:,:,3]
coluna3todasfaces

array([[0.29831892, 0.33208354, 0.24980908, 0.83300326],
       [0.62288818, 0.44535229, 0.89487463, 0.35008089],
       [0.81918305, 0.97400712, 0.17155262, 0.86394872]])

### Indexação com booleanos

In [44]:
a2D = np.random.randint(1, 501, (10, 8)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[ 92, 258,  69, 237, 465,  92, 381,  30],
       [ 93, 326, 425, 198, 272, 443, 431, 486],
       [488, 132, 110, 134, 157, 256, 241, 409],
       [215, 399, 283, 484, 447, 347, 464, 464],
       [ 86, 290, 227, 481, 304, 424, 250, 122],
       [392,  75, 135, 341,  49, 393, 493,  47],
       [ 46, 467, 319, 166, 453, 285, 368, 400],
       [353, 466, 173,  63, 110, 411, 267, 461],
       [270, 337,  62,  36, 147, 265, 241,  85],
       [ 22, 280, 238, 308,  57, 365, 407, 280]])

In [45]:
a2D >= 250

array([[False,  True, False, False,  True, False,  True, False],
       [False,  True,  True, False,  True,  True,  True,  True],
       [ True, False, False, False, False,  True, False,  True],
       [False,  True,  True,  True,  True,  True,  True,  True],
       [False,  True, False,  True,  True,  True,  True, False],
       [ True, False, False,  True, False,  True,  True, False],
       [False,  True,  True, False,  True,  True,  True,  True],
       [ True,  True, False, False, False,  True,  True,  True],
       [ True,  True, False, False, False,  True, False, False],
       [False,  True, False,  True, False,  True,  True,  True]])

In [46]:
a2D[a2D >= 250]

array([258, 465, 381, 326, 425, 272, 443, 431, 486, 488, 256, 409, 399,
       283, 484, 447, 347, 464, 464, 290, 481, 304, 424, 250, 392, 341,
       393, 493, 467, 319, 453, 285, 368, 400, 353, 466, 411, 267, 461,
       270, 337, 265, 280, 308, 365, 407, 280])

In [47]:
a2D.mean()

270.5625

In [48]:
a2D[a2D <= a2D.mean()]

array([ 92, 258,  69, 237,  92,  30,  93, 198, 132, 110, 134, 157, 256,
       241, 215,  86, 227, 250, 122,  75, 135,  49,  47,  46, 166, 173,
        63, 110, 267, 270,  62,  36, 147, 265, 241,  85,  22, 238,  57])