<a href="https://colab.research.google.com/github/aliceylu/python/blob/main/Aula_Numpy_04_Manipulac%CC%A7a%CC%83o_de_Arrays_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipulação de arrays Numpy

### Importando o NumPy

In [1]:
# Importando o NumPy
import numpy as np

### Alterando, adicionando e removendo elementos

In [2]:
# Criando um array de 1 dimensão
a1D = np.random.randint(1,200, 12)
a1D

array([135, 127, 173, 183, 185, 190,  56,  21,  10,  31,  69,  22])

In [3]:
# Criando um array de 2 dimensões
a2D = np.random.randint(1,200, (3,4))
a2D

array([[ 37, 136,  37,  56],
       [119,  73,  24, 167],
       [190,  63,  27,  42]])

In [4]:
# Criando um array de 3 dimensões
a3D = np.random.randint(1,200, (2,3,6)) # 2 páginas/faces, 3 linhas, 6 colunas
a3D

array([[[108,   8,  75,  48, 107, 156],
        [190, 104, 174, 191,  49,  81],
        [  5,  90, 172,  45,  16, 156]],

       [[ 16,  75, 191, 131, 179,  32],
        [ 70, 180, 144,  88, 114, 119],
        [ 27, 107, 152, 168, 106,  93]]])

In [5]:
# Alterando o elemento do índice 0
a1D[0] = -1
a1D

array([ -1, 127, 173, 183, 185, 190,  56,  21,  10,  31,  69,  22])

In [6]:
# Alterando o elemento da linha 1, coluna 2
a2D[1][2] = -1
a2D

array([[ 37, 136,  37,  56],
       [119,  73,  -1, 167],
       [190,  63,  27,  42]])

In [7]:
# Alterando o elemento da face 1, linha 2, coluna 4
a3D[1][2][4] = -1
a3D

array([[[108,   8,  75,  48, 107, 156],
        [190, 104, 174, 191,  49,  81],
        [  5,  90, 172,  45,  16, 156]],

       [[ 16,  75, 191, 131, 179,  32],
        [ 70, 180, 144,  88, 114, 119],
        [ 27, 107, 152, 168,  -1,  93]]])

In [8]:
# Retorna array com elementos adicionados no final
a1D_modificado = np.append(a1D, [100, 130])
a1D_modificado

array([ -1, 127, 173, 183, 185, 190,  56,  21,  10,  31,  69,  22, 100,
       130])

In [9]:
a1D # a1D não foi modificado

array([ -1, 127, 173, 183, 185, 190,  56,  21,  10,  31,  69,  22])

In [10]:
a2D_modificado = np.append(a2D, [100, 130]) # Lineariza a2D e insere os elementos no final
a2D_modificado

array([ 37, 136,  37,  56, 119,  73,  -1, 167, 190,  63,  27,  42, 100,
       130])

In [11]:
a2D # a2D não foi modificado

array([[ 37, 136,  37,  56],
       [119,  73,  -1, 167],
       [190,  63,  27,  42]])

In [12]:
a3D_modificado = np.append(a3D, [100, 130]) # Lineariza a3D e insere os elementos no final
a3D_modificado

array([108,   8,  75,  48, 107, 156, 190, 104, 174, 191,  49,  81,   5,
        90, 172,  45,  16, 156,  16,  75, 191, 131, 179,  32,  70, 180,
       144,  88, 114, 119,  27, 107, 152, 168,  -1,  93, 100, 130])

In [13]:
a3D # a3D não foi modificado

array([[[108,   8,  75,  48, 107, 156],
        [190, 104, 174, 191,  49,  81],
        [  5,  90, 172,  45,  16, 156]],

       [[ 16,  75, 191, 131, 179,  32],
        [ 70, 180, 144,  88, 114, 119],
        [ 27, 107, 152, 168,  -1,  93]]])

In [14]:
a1D_modificado2 = np.delete(a1D_modificado, [0, 1, 3])
print(a1D_modificado)
print(a1D_modificado2)

[ -1 127 173 183 185 190  56  21  10  31  69  22 100 130]
[173 185 190  56  21  10  31  69  22 100 130]


### Comparação entre arrays

In [15]:
a1D = np.array([1, 2, 3, 4, 5])
b1D = np.array([3, 2, 1, 4, 5])
a1D == b1D # Comparação elemento a elemento

array([False,  True, False,  True,  True])

In [16]:
c1D = np.random.randint(1,10,20)
c1D

array([3, 8, 2, 1, 1, 1, 5, 9, 7, 4, 3, 9, 5, 5, 9, 4, 6, 1, 3, 8])

In [17]:
c1D == 5

array([False, False, False, False, False, False,  True, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False])

In [18]:
c1D[c1D == 5]

array([5, 5, 5])

### Operações entre arrays e escalares

In [19]:
a1D = np.arange(1,11)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
b1D = np.arange(1,20,2)
b1D

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
c1D = 2 * a1D # Cada elemento de a1D será multiplicado por 2
c1D

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
d1D = b1D + 5 # Soma 5 para cada elemento de b1D
d1D

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [23]:
e1D = b1D - 3
e1D

array([-2,  0,  2,  4,  6,  8, 10, 12, 14, 16])

In [24]:
f1D = a1D / 5
f1D

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [25]:
celsius = np.arange(-20, 36) # Cria um array com o valores de -20 a 35, representando a temperatura em graus Celsius
fahrenheit = celsius * (9/5) + 32 # Cria um array convertendo cada valor em Celsius para fahrenheit

fahrenheit

array([-4. , -2.2, -0.4,  1.4,  3.2,  5. ,  6.8,  8.6, 10.4, 12.2, 14. ,
       15.8, 17.6, 19.4, 21.2, 23. , 24.8, 26.6, 28.4, 30.2, 32. , 33.8,
       35.6, 37.4, 39.2, 41. , 42.8, 44.6, 46.4, 48.2, 50. , 51.8, 53.6,
       55.4, 57.2, 59. , 60.8, 62.6, 64.4, 66.2, 68. , 69.8, 71.6, 73.4,
       75.2, 77. , 78.8, 80.6, 82.4, 84.2, 86. , 87.8, 89.6, 91.4, 93.2,
       95. ])

In [26]:
# Somando cada elemento de a1D a b1D
g1D = a1D + b1D
print(a1D)
print(b1D)
print("-"*31)
print(g1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [27]:
# Outra forma de somar cada elemento de a1D a b1D
h1D = np.add(a1D, b1D)
print(a1D)
print(b1D)
print("-"*31)
print(h1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [28]:
i1D = h1D - g1D
print(h1D)
print(g1D)
print("-"*31)
print(i1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [29]:
# Outra forma de somar cada elemento de a1D a b1D
j1D = np.subtract(h1D, g1D)
print(h1D)
print(g1D)
print("-"*31)
print(j1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [30]:
a1D = np.arange(1, 6)
a1D

array([1, 2, 3, 4, 5])

In [31]:
b1D = np.arange(6,11)
b1D

array([ 6,  7,  8,  9, 10])

In [32]:
c1D = a1D * b1D
c1D

array([ 6, 14, 24, 36, 50])

In [33]:
d1D = np.multiply(a1D, b1D)
d1D

array([ 6, 14, 24, 36, 50])

In [34]:
e1D = c1D / a1D
e1D

array([ 6.,  7.,  8.,  9., 10.])

In [35]:
f1D = np.divide(c1D, a1D)
f1D

array([ 6.,  7.,  8.,  9., 10.])

In [36]:
g1D = np.arange(1,10)
g1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
raiz1D = np.sqrt(g1D)
raiz1D

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

### Algumas funções

1D - dimensão coluna
2D - 2 eixos. 0 -> coluna 1 -> linha
3D - 3 eixos. 0 -> coluna 1 -> linha 2 -> faces

In [50]:
d2D = np.random.randint(1, 101, (5,10)) # Array de 5 linhas x 10 colunas preenchidos com valores aleatórios entre 1 e 100
d2D

array([[60, 41, 44, 60, 49, 46, 18, 26,  6, 83],
       [89, 58, 63, 36, 58, 59, 43, 23, 68, 75],
       [35, 46, 10,  2, 32, 50, 12, 36, 30, 72],
       [58, 40, 90, 75, 43, 34, 26, 26, 82, 54],
       [76, 34, 89, 53, 18,  7,  6, 89, 30, 85]])

#### Obs: como os valores valores são gerados aleatoriamente, sua matriz provavelmente será diferente da gerada acima

In [51]:
# Soma de todos os elementos
d2D.sum()

2345

In [52]:
# Soma de todos os elementos de cada coluna (eixo 0)
d2D.sum(axis = 0)

array([318, 219, 296, 226, 200, 196, 105, 200, 216, 369])

In [53]:
# Soma de todos os elementos de cada linha (eixo 1)
d2D.sum(axis = 1)

array([433, 572, 325, 528, 487])

In [54]:
somacol = sum(d2D) # A função sum() do Python retornará a soma de todas as colunas
somacol

array([318, 219, 296, 226, 200, 196, 105, 200, 216, 369])

In [55]:
# Retorna o menor valor geral
d2D.min()

2

In [56]:
# Retorna o menor valor de cada coluna (eixo 0)
d2D.min(axis=0)

array([35, 34, 10,  2, 18,  7,  6, 23,  6, 54])

In [57]:
# Retorna o menor valor de cada linha (eixo 1)
d2D.min(axis=1)

array([ 6, 23,  2, 26,  6])

In [58]:
# Retorna o maior valor geral
d2D.max()

90

In [59]:
# Retorna o maior valor de cada coluna (eixo 0)
d2D.max(axis=0)

array([89, 58, 90, 75, 58, 59, 43, 89, 82, 85])

In [60]:
# Retorna o maior valor de cada linha (eixo 1)
d2D.max(axis=1)

array([83, 89, 72, 90, 89])

In [61]:
# Retorna a soma cumulativa
d2D.cumsum()

array([  60,  101,  145,  205,  254,  300,  318,  344,  350,  433,  522,
        580,  643,  679,  737,  796,  839,  862,  930, 1005, 1040, 1086,
       1096, 1098, 1130, 1180, 1192, 1228, 1258, 1330, 1388, 1428, 1518,
       1593, 1636, 1670, 1696, 1722, 1804, 1858, 1934, 1968, 2057, 2110,
       2128, 2135, 2141, 2230, 2260, 2345])

In [62]:
# Retorna a soma cumulativa para cada coluna (eixo = 0)
d2D.cumsum(axis = 0)

array([[ 60,  41,  44,  60,  49,  46,  18,  26,   6,  83],
       [149,  99, 107,  96, 107, 105,  61,  49,  74, 158],
       [184, 145, 117,  98, 139, 155,  73,  85, 104, 230],
       [242, 185, 207, 173, 182, 189,  99, 111, 186, 284],
       [318, 219, 296, 226, 200, 196, 105, 200, 216, 369]])

In [63]:
d2D

array([[60, 41, 44, 60, 49, 46, 18, 26,  6, 83],
       [89, 58, 63, 36, 58, 59, 43, 23, 68, 75],
       [35, 46, 10,  2, 32, 50, 12, 36, 30, 72],
       [58, 40, 90, 75, 43, 34, 26, 26, 82, 54],
       [76, 34, 89, 53, 18,  7,  6, 89, 30, 85]])

In [64]:
# Retorna a soma cumulativa para cada linha (eixo = 1)
x = d2D.cumsum(axis = 1)
x

array([[ 60, 101, 145, 205, 254, 300, 318, 344, 350, 433],
       [ 89, 147, 210, 246, 304, 363, 406, 429, 497, 572],
       [ 35,  81,  91,  93, 125, 175, 187, 223, 253, 325],
       [ 58,  98, 188, 263, 306, 340, 366, 392, 474, 528],
       [ 76, 110, 199, 252, 270, 277, 283, 372, 402, 487]])

In [66]:
# Retorna a média aritmética
d2D.mean()

46.9

In [67]:
# Retorna a média aritmética para cada coluna (eixo = 0)
d2D.mean(axis = 0)

array([63.6, 43.8, 59.2, 45.2, 40. , 39.2, 21. , 40. , 43.2, 73.8])

In [68]:
# Retorna a média aritmética para cada linha (eixo = 1)
d2D.mean(axis = 1)

array([43.3, 57.2, 32.5, 52.8, 48.7])

In [69]:
# Retorna o desvio padrão
d2D.std()

24.737218922101974

In [70]:
# Retorna o desvio padrão para cada coluna (eixo = 0)
d2D.std(axis = 0)

array([18.22745182,  8.05977667, 30.00933188, 24.97518769, 13.87083271,
       17.9933321 , 12.83744523, 24.89176571, 27.75896252, 11.01635148])

In [71]:
# Retorna o desvio padrão para cada linha (eixo = 1)
d2D.std(axis = 1)

array([21.23699602, 18.1758081 , 19.82548864, 21.92623999, 32.24918604])

In [72]:
# Retorna a mediana (geral)
np.median(d2D)

45.0

In [73]:
# Retorna a mediana para cada coluna (eixo = 0)
np.median(d2D, axis = 0)

array([60., 41., 63., 53., 43., 46., 18., 26., 30., 75.])

In [74]:
# Retorna a mediana para cada linha (eixo = 1)
np.median(d2D, axis = 1)

array([45. , 58.5, 33.5, 48.5, 43.5])

### Copiando e concatenando arrays

In [75]:
a2D = np.random.randint(1,50, (4,5))
a2D

array([[14, 12, 21,  5, 26],
       [ 6, 42, 45, 40,  6],
       [44, 25, 14, 35, 38],
       [34,  2, 25, 47,  9]])

In [76]:
b2D = np.random.randint(50,100, (4,5))
b2D

array([[83, 88, 98, 86, 70],
       [62, 56, 67, 87, 76],
       [95, 69, 66, 71, 59],
       [70, 70, 66, 73, 90]])

In [77]:
c2D = a2D
c2D

array([[14, 12, 21,  5, 26],
       [ 6, 42, 45, 40,  6],
       [44, 25, 14, 35, 38],
       [34,  2, 25, 47,  9]])

In [78]:
# Aparentemente ocorreu uma cópia dos arrays, mas veja o que acontece se alterarmos alguns elementos
c2D[c2D < 20] = -1
c2D

array([[-1, -1, 21, -1, 26],
       [-1, 42, 45, 40, -1],
       [44, 25, -1, 35, 38],
       [34, -1, 25, 47, -1]])

In [79]:
a2D

array([[-1, -1, 21, -1, 26],
       [-1, 42, 45, 40, -1],
       [44, 25, -1, 35, 38],
       [34, -1, 25, 47, -1]])

Os elementos de a2D também foram alterados. :-(

In [81]:
# Redefinindo os elementos de a2D
a2D = np.random.randint(1,50, (4,5))
a2D

array([[ 5, 28,  4, 35, 10],
       [41,  1, 46, 34, 40],
       [41,  6, 37, 41, 31],
       [36, 28, 26,  4, 37]])

In [82]:
# Forma correta de copiar um array parece que com a forma de copiar uma lista
c2D = a2D.copy()
c2D

array([[ 5, 28,  4, 35, 10],
       [41,  1, 46, 34, 40],
       [41,  6, 37, 41, 31],
       [36, 28, 26,  4, 37]])

In [83]:
c2D[c2D < 20] = -1
c2D

array([[-1, 28, -1, 35, -1],
       [41, -1, 46, 34, 40],
       [41, -1, 37, 41, 31],
       [36, 28, 26, -1, 37]])

In [84]:
a2D

array([[ 5, 28,  4, 35, 10],
       [41,  1, 46, 34, 40],
       [41,  6, 37, 41, 31],
       [36, 28, 26,  4, 37]])

Agora sim!!!

### Ordenando os elementos de um array

In [85]:
a1D = np.random.randint(1,100, 15)
a1D

array([15, 73, 19, 72, 19, 16, 84, 85, 69, 13, 80, 33, 90, 91, 30])

In [86]:
a1D.sort()
a1D

array([13, 15, 16, 19, 19, 30, 33, 69, 72, 73, 80, 84, 85, 90, 91])

In [89]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[19, 22, 31, 74, 61, 32, 61, 56, 46, 71],
       [45, 38, 11, 57, 57, 34, 30, 43, 65, 68],
       [79, 91, 52, 94, 42, 96, 16, 54, 24, 85],
       [46, 28,  8, 85, 72, 39, 85, 99, 95, 10],
       [95, 23, 14, 17, 14, 61, 80, 71,  2, 89],
       [34, 12, 17,  5, 58, 93, 43, 85, 77, 65]])

In [90]:
a2D.sort() # Por padrão ordena o maior eixo (nesse caso o eixo 1, linhas)
a2D

array([[19, 22, 31, 32, 46, 56, 61, 61, 71, 74],
       [11, 30, 34, 38, 43, 45, 57, 57, 65, 68],
       [16, 24, 42, 52, 54, 79, 85, 91, 94, 96],
       [ 8, 10, 28, 39, 46, 72, 85, 85, 95, 99],
       [ 2, 14, 14, 17, 23, 61, 71, 80, 89, 95],
       [ 5, 12, 17, 34, 43, 58, 65, 77, 85, 93]])

In [91]:
a2D.sort(axis=0) # Ordenando pelo eixo 0 (colunas)
a2D

array([[ 2, 10, 14, 17, 23, 45, 57, 57, 65, 68],
       [ 5, 12, 17, 32, 43, 56, 61, 61, 71, 74],
       [ 8, 14, 28, 34, 43, 58, 65, 77, 85, 93],
       [11, 22, 31, 38, 46, 61, 71, 80, 89, 95],
       [16, 24, 34, 39, 46, 72, 85, 85, 94, 96],
       [19, 30, 42, 52, 54, 79, 85, 91, 95, 99]])

In [92]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[49, 27, 68, 47, 22, 20, 33, 88,  5, 53],
       [ 4, 98, 41, 71, 98,  5, 75, 25, 17, 40],
       [12, 18, 93, 86, 77, 74, 22,  4, 16, 32],
       [59, 27, 93, 47, 32, 57, 72, 59, 90, 46],
       [ 5, 35,  3, 88, 49,  6, 47, 40, 28, 33],
       [88, 16, 52, 47, 32,  9, 62, 15, 40, 56]])

In [93]:
a2D.sort(axis=1) # Ordenando pelo eixo 1 (linhas)
a2D

array([[ 5, 20, 22, 27, 33, 47, 49, 53, 68, 88],
       [ 4,  5, 17, 25, 40, 41, 71, 75, 98, 98],
       [ 4, 12, 16, 18, 22, 32, 74, 77, 86, 93],
       [27, 32, 46, 47, 57, 59, 59, 72, 90, 93],
       [ 3,  5,  6, 28, 33, 35, 40, 47, 49, 88],
       [ 9, 15, 16, 32, 40, 47, 52, 56, 62, 88]])

### Transposição de arrays

In [94]:
a2D = np.array([[1,2,3,4],[5,6,7,8]])
a2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
a2DT = a2D.T # Retorna a transposta
a2DT

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [96]:
a2D # a2D original não foi transposto

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [97]:
a2D.transpose() # Retorna a transposta

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [99]:
a2D # a2D original não foi transposto (não é método inplace)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Mudando o formato de um array - reshape()

In [110]:
a1D = np.arange(1,25)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [111]:
print(a1D.shape)
a1D.shape = (2,12)
print(a1D.shape)
print(a1D)

(24,)
(2, 12)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [114]:
a2D_4x6 = a1D.reshape(4,6) #não altera o formato do array, mas retorna o array formatado
a2D_4x6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [115]:
a1D

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [116]:
a2D_3x8 = a1D.reshape(3,8)
a2D_3x8

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

### Linearização de um array

In [117]:
x = a2D_3x8.flatten()
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [118]:
y = a2D_3x8.ravel()
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

### Combinando/concatenando arrays

In [119]:
a2D = np.random.randint(1,101,(3,9))
a2D

array([[41, 79, 70, 79, 69, 20, 60, 81, 46],
       [97, 86, 22, 53, 76, 35, 24, 10, 56],
       [40, 44, 80, 64, 44,  2, 95, 15, 31]])

In [120]:
b2D = np.random.randint(1,101,(5,9))
b2D

array([[84,  5, 87, 60, 34, 38, 68,  4,  1],
       [32, 45, 46, 76, 36,  4, 99, 41, 67],
       [88, 17, 71,  9, 64, 38, 86, 54,  6],
       [58, 93, 96, 99, 20, 62, 13, 74, 38],
       [60, 42, 96, 64, 87,  7, 77, 53, 69]])

In [121]:
c2D = np.random.randint(1,101,(5,4))
c2D

array([[52, 52,  9, 62],
       [38, 69, 35, 97],
       [79, 70, 28, 99],
       [42, 32, 98, 44],
       [95, 56, 81, 78]])

In [122]:
# Concatenação de strings usa o operador "+"
str1 = "Python"
str2 = " & "
str3 = "Numpy"
str4 = str1 + str2 + str3
str4

'Python & Numpy'

In [123]:
# O operador "+" aplicado a ndarrays não faz a concatenação, mas tentar somar elemento a elemento
a2D + b2D

ValueError: operands could not be broadcast together with shapes (3,9) (5,9) 

In [124]:
A = np.concatenate((a2D, b2D), axis = 0) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical)
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(A)

a2D
[[41 79 70 79 69 20 60 81 46]
 [97 86 22 53 76 35 24 10 56]
 [40 44 80 64 44  2 95 15 31]]

b2D
[[84  5 87 60 34 38 68  4  1]
 [32 45 46 76 36  4 99 41 67]
 [88 17 71  9 64 38 86 54  6]
 [58 93 96 99 20 62 13 74 38]
 [60 42 96 64 87  7 77 53 69]]

Concatenação
[[41 79 70 79 69 20 60 81 46]
 [97 86 22 53 76 35 24 10 56]
 [40 44 80 64 44  2 95 15 31]
 [84  5 87 60 34 38 68  4  1]
 [32 45 46 76 36  4 99 41 67]
 [88 17 71  9 64 38 86 54  6]
 [58 93 96 99 20 62 13 74 38]
 [60 42 96 64 87  7 77 53 69]]


In [125]:
B = np.vstack((a2D, b2D)) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical)
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(B)

a2D
[[41 79 70 79 69 20 60 81 46]
 [97 86 22 53 76 35 24 10 56]
 [40 44 80 64 44  2 95 15 31]]

b2D
[[84  5 87 60 34 38 68  4  1]
 [32 45 46 76 36  4 99 41 67]
 [88 17 71  9 64 38 86 54  6]
 [58 93 96 99 20 62 13 74 38]
 [60 42 96 64 87  7 77 53 69]]

Concatenação
[[41 79 70 79 69 20 60 81 46]
 [97 86 22 53 76 35 24 10 56]
 [40 44 80 64 44  2 95 15 31]
 [84  5 87 60 34 38 68  4  1]
 [32 45 46 76 36  4 99 41 67]
 [88 17 71  9 64 38 86 54  6]
 [58 93 96 99 20 62 13 74 38]
 [60 42 96 64 87  7 77 53 69]]


In [126]:
C = np.concatenate((b2D, c2D), axis = 1) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal)
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(C)

b2D
[[84  5 87 60 34 38 68  4  1]
 [32 45 46 76 36  4 99 41 67]
 [88 17 71  9 64 38 86 54  6]
 [58 93 96 99 20 62 13 74 38]
 [60 42 96 64 87  7 77 53 69]]

c2D
[[52 52  9 62]
 [38 69 35 97]
 [79 70 28 99]
 [42 32 98 44]
 [95 56 81 78]]

Concatenação
[[84  5 87 60 34 38 68  4  1 52 52  9 62]
 [32 45 46 76 36  4 99 41 67 38 69 35 97]
 [88 17 71  9 64 38 86 54  6 79 70 28 99]
 [58 93 96 99 20 62 13 74 38 42 32 98 44]
 [60 42 96 64 87  7 77 53 69 95 56 81 78]]


In [127]:
D = np.hstack((b2D, c2D)) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal)
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(D)

b2D
[[84  5 87 60 34 38 68  4  1]
 [32 45 46 76 36  4 99 41 67]
 [88 17 71  9 64 38 86 54  6]
 [58 93 96 99 20 62 13 74 38]
 [60 42 96 64 87  7 77 53 69]]

c2D
[[52 52  9 62]
 [38 69 35 97]
 [79 70 28 99]
 [42 32 98 44]
 [95 56 81 78]]

Concatenação
[[84  5 87 60 34 38 68  4  1 52 52  9 62]
 [32 45 46 76 36  4 99 41 67 38 69 35 97]
 [88 17 71  9 64 38 86 54  6 79 70 28 99]
 [58 93 96 99 20 62 13 74 38 42 32 98 44]
 [60 42 96 64 87  7 77 53 69 95 56 81 78]]


### Dividindo arrays

In [128]:
A_splitted = np.vsplit(A,2) # Divisáo vertical (corta no sentido das colunas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted[0])
print("")
print("2a parte")
print(A_splitted[1])

Array original
[[41 79 70 79 69 20 60 81 46]
 [97 86 22 53 76 35 24 10 56]
 [40 44 80 64 44  2 95 15 31]
 [84  5 87 60 34 38 68  4  1]
 [32 45 46 76 36  4 99 41 67]
 [88 17 71  9 64 38 86 54  6]
 [58 93 96 99 20 62 13 74 38]
 [60 42 96 64 87  7 77 53 69]]

1a parte
[[41 79 70 79 69 20 60 81 46]
 [97 86 22 53 76 35 24 10 56]
 [40 44 80 64 44  2 95 15 31]
 [84  5 87 60 34 38 68  4  1]]

2a parte
[[32 45 46 76 36  4 99 41 67]
 [88 17 71  9 64 38 86 54  6]
 [58 93 96 99 20 62 13 74 38]
 [60 42 96 64 87  7 77 53 69]]


In [129]:
A_splitted3 = np.hsplit(A,3) # Divisão horizontal (corta no sentido das linhas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted3[0])
print("")
print("2a parte")
print(A_splitted3[1])
print("")
print("3a parte")
print(A_splitted3[2])

Array original
[[41 79 70 79 69 20 60 81 46]
 [97 86 22 53 76 35 24 10 56]
 [40 44 80 64 44  2 95 15 31]
 [84  5 87 60 34 38 68  4  1]
 [32 45 46 76 36  4 99 41 67]
 [88 17 71  9 64 38 86 54  6]
 [58 93 96 99 20 62 13 74 38]
 [60 42 96 64 87  7 77 53 69]]

1a parte
[[41 79 70]
 [97 86 22]
 [40 44 80]
 [84  5 87]
 [32 45 46]
 [88 17 71]
 [58 93 96]
 [60 42 96]]

2a parte
[[79 69 20]
 [53 76 35]
 [64 44  2]
 [60 34 38]
 [76 36  4]
 [ 9 64 38]
 [99 20 62]
 [64 87  7]]

3a parte
[[60 81 46]
 [24 10 56]
 [95 15 31]
 [68  4  1]
 [99 41 67]
 [86 54  6]
 [13 74 38]
 [77 53 69]]
